### ISSUE TITLE
`lpc845-test-assistant` doesn't build with latest `lpc8xx-hal` commit

### ISSUE THREAD

**Issue by Lotterleben** [braun-embedded/embedded-test-stand#108]
The `"lpc8xx-hal"` dependency in  `lpc845-test-stand/test-assistant/Cargo.lock` is still at`401d73d6a3f2c643d4d496d856c727b59bada6af`, but the latest hal commit is `bec1cf72a00d86beaeaa43bea78e39542db12888`. 

When I update this dep to `bec1cf72a00d86beaeaa43bea78e39542db12888` by changing

```diff
-source = "git+https://github.com/lpc-rs/lpc8xx-hal.git#401d73d6a3f2c643d4d496d856c727b59bada6af"
+source = "git+https://github.com/lpc-rs/lpc8xx-hal.git#bec1cf72a00d86beaeaa43bea78e39542db12888"
```

I get the following error while building:

```console
➜  test-assistant git:(master) ✗ cargo build
   Compiling lpc8xx-hal v0.8.2 (https://github.com/lpc-rs/lpc8xx-hal.git#bec1cf72)
   Compiling firmware-lib v0.1.0 (/<redacted>/embedded-test-stand/test-stand-infra/firmware-lib)
error[E0369]: cannot subtract `u32` from `lpc8xx_hal::mrt::Ticks`
   --> /<redacted>/embedded-test-stand/test-stand-infra/firmware-lib/src/pin_interrupt.rs:100:46
    |
100 |                 period = Some(mrt::MAX_VALUE - self.timer.value());
    |                               -------------- ^ ------------------ u32
    |                               |
    |                               lpc8xx_hal::mrt::Ticks

error: aborting due to previous error

For more information about this error, try `rustc --explain E0369`.
error: could not compile `firmware-lib`.
```
(maybe due to src/mrt.rs:69 in https://github.com/lpc-rs/lpc8xx-hal/pull/298 ?)

Is this on purpose?

**Comment by hannobraun** [comment]
Yes, that's definitely https://github.com/lpc-rs/lpc8xx-hal/pull/298. I mean, I didn't try to break the build here specifically, but I knew this was a breaking change, so yes, it's on purpose :-)

Now that I'm looking at it again, this does expose some problems with that pull request though:

1. There doesn't seem to be a way to convert `Ticks` to `u32`. There should definitely be an `Into<u32>` implementation, and maybe an inherent method that does the same (`Ticks::value`?).
2. That `Channel::value` and `Channel::reload_value` return `u32` and not `Tick` is questionable. That deserves another look.

I've made a note to look into this, but it's unlikely I'll get to it before January. Feel free to submit a pull request upstream.

**Comment by Lotterleben** [comment]
Okay, cool! I've added a similar quick fix to my codebase, should be convertible to a PR :) I'm wondering, would adding `Into<Nanoseconds>`, `Into<Milliseconds>`.. etc be useful too while we're at it?

**Comment by hannobraun** [comment]
> Okay, cool! I've added a similar quick fix to my codebase, should be convertible to a PR :) I'm wondering, would adding `Into<Nanoseconds>`, `Into<Milliseconds>`.. etc be useful too while we're at it?

Good idea, that sounds useful.
